# Gradle / JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true

# AndroidX & Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.version=1.9.0
kotlin.compiler.execution.strategy=in-process

# Expo / React Native
expo.jsEngine=hermes
expo.modules.updates.enabled=true
newArchEnabled=false
